import type { PatronNegocio } from '../types/bac'

const p = (x: number, y: number) => ({ x, y })

export const PATRONES: PatronNegocio[] = [
  {
    id: 1,
    nombre: 'P1 – Comercio Minorista',
    descripcion: 'Venta directa de productos físicos al consumidor final.',
    categoria: 'Distribución',
    ejemplo: 'Supermercado, tienda de ropa',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(100, 200), data: { label: 'Negocio', tipo: 'negocio', descripcion: 'Empresa minorista' } },
      { id: 'n2', type: 'bacNode', position: p(400, 100), data: { label: 'Cliente', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(400, 300), data: { label: 'Proveedor', tipo: 'proveedor' } },
      { id: 'n4', type: 'bacNode', position: p(250, 200), data: { label: 'Canal D', tipo: 'canal', canalTipo: 'D', descripcion: 'Canal de distribución física' } },
      { id: 'n5', type: 'bacNode', position: p(250, 350), data: { label: 'Canal M', tipo: 'canal', canalTipo: 'M', descripcion: 'Cobro al cliente' } },
      { id: 'n6', type: 'bacNode', position: p(550, 200), data: { label: 'Producto Físico', tipo: 'componente', descripcion: 'Inventario de productos' } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n4', type: 'smoothstep' },
      { id: 'e2', source: 'n4', target: 'n2', type: 'smoothstep' },
      { id: 'e3', source: 'n3', target: 'n1', type: 'smoothstep' },
      { id: 'e4', source: 'n2', target: 'n5', type: 'smoothstep' },
      { id: 'e5', source: 'n5', target: 'n1', type: 'smoothstep' },
      { id: 'e6', source: 'n4', target: 'n6', type: 'smoothstep' },
    ],
  },
  {
    id: 2,
    nombre: 'P2 – Alquiler de Activos Propios',
    descripcion: 'Alquiler de activos físicos propios a terceros.',
    categoria: 'Activos',
    ejemplo: 'Hotel, arrendadora de vehículos',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(100, 200), data: { label: 'Negocio', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(450, 150), data: { label: 'Cliente', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(280, 150), data: { label: 'Canal R', tipo: 'canal', canalTipo: 'R', descripcion: 'Reserva y relación' } },
      { id: 'n4', type: 'bacNode', position: p(280, 300), data: { label: 'Canal M', tipo: 'canal', canalTipo: 'M', descripcion: 'Cobro por uso' } },
      { id: 'n5', type: 'bacNode', position: p(450, 300), data: { label: 'Activo Físico', tipo: 'componente', descripcion: 'Bien durable propio' } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n3', type: 'smoothstep' },
      { id: 'e2', source: 'n3', target: 'n2', type: 'smoothstep' },
      { id: 'e3', source: 'n2', target: 'n4', type: 'smoothstep' },
      { id: 'e4', source: 'n4', target: 'n1', type: 'smoothstep' },
      { id: 'e5', source: 'n5', target: 'n3', type: 'smoothstep' },
    ],
  },
  {
    id: 3,
    nombre: 'P3 – Manufactura',
    descripcion: 'Transformación de materias primas en productos terminados.',
    categoria: 'Transformación',
    ejemplo: 'Fábrica textil, planta de alimentos',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(100, 250), data: { label: 'Negocio', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(450, 100), data: { label: 'Cliente B2B', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(100, 450), data: { label: 'Proveedor Mat.', tipo: 'proveedor' } },
      { id: 'n4', type: 'bacNode', position: p(280, 250), data: { label: 'Canal T', tipo: 'canal', canalTipo: 'T', descripcion: 'Transformación productiva' } },
      { id: 'n5', type: 'bacNode', position: p(280, 100), data: { label: 'Canal D', tipo: 'canal', canalTipo: 'D', descripcion: 'Distribución B2B' } },
      { id: 'n6', type: 'bacNode', position: p(280, 400), data: { label: 'Canal A', tipo: 'canal', canalTipo: 'A', descripcion: 'Aprovisionamiento de insumos' } },
      { id: 'n7', type: 'bacNode', position: p(500, 250), data: { label: 'Producto Final', tipo: 'componente' } },
    ],
    edges: [
      { id: 'e1', source: 'n3', target: 'n6', type: 'smoothstep' },
      { id: 'e2', source: 'n6', target: 'n1', type: 'smoothstep' },
      { id: 'e3', source: 'n1', target: 'n4', type: 'smoothstep' },
      { id: 'e4', source: 'n4', target: 'n7', type: 'smoothstep' },
      { id: 'e5', source: 'n7', target: 'n5', type: 'smoothstep' },
      { id: 'e6', source: 'n5', target: 'n2', type: 'smoothstep' },
    ],
  },
  {
    id: 4,
    nombre: 'P4 – Alquiler de Activos de Terceros',
    descripcion: 'Plataforma que conecta dueños de activos con usuarios que los necesitan.',
    categoria: 'Plataforma',
    ejemplo: 'Airbnb, Turo',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(350, 250), data: { label: 'Plataforma', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(600, 150), data: { label: 'Huésped', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(600, 350), data: { label: 'Anfitrión', tipo: 'actor', actorTipo: 'usuario' } },
      { id: 'n4', type: 'bacNode', position: p(100, 150), data: { label: 'Activo Tercero', tipo: 'componente', descripcion: 'Inmueble del anfitrión' } },
      { id: 'n5', type: 'bacNode', position: p(480, 150), data: { label: 'Canal R', tipo: 'canal', canalTipo: 'R', descripcion: 'Matching demanda/oferta' } },
      { id: 'n6', type: 'bacNode', position: p(480, 350), data: { label: 'Canal M', tipo: 'canal', canalTipo: 'M', descripcion: 'Comisión transacción' } },
    ],
    edges: [
      { id: 'e1', source: 'n3', target: 'n4', type: 'smoothstep' },
      { id: 'e2', source: 'n4', target: 'n5', type: 'smoothstep' },
      { id: 'e3', source: 'n5', target: 'n2', type: 'smoothstep' },
      { id: 'e4', source: 'n2', target: 'n6', type: 'smoothstep' },
      { id: 'e5', source: 'n6', target: 'n1', type: 'smoothstep' },
      { id: 'e6', source: 'n1', target: 'n5', type: 'smoothstep' },
    ],
  },
  {
    id: 5,
    nombre: 'P5 – Gestión de Dinero',
    descripcion: 'Captación y colocación de dinero con margen financiero.',
    categoria: 'Financiero',
    ejemplo: 'Banco, cooperativa de ahorro',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(300, 250), data: { label: 'Entidad Financiera', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(550, 100), data: { label: 'Ahorradores', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(550, 400), data: { label: 'Deudores', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n4', type: 'bacNode', position: p(100, 250), data: { label: 'Capital', tipo: 'componente', descripcion: 'Depósito de dinero' } },
      { id: 'n5', type: 'bacNode', position: p(420, 100), data: { label: 'Canal M-captación', tipo: 'canal', canalTipo: 'M', descripcion: 'Captación de depósitos' } },
      { id: 'n6', type: 'bacNode', position: p(420, 400), data: { label: 'Canal M-colocación', tipo: 'canal', canalTipo: 'M', descripcion: 'Colocación de créditos' } },
    ],
    edges: [
      { id: 'e1', source: 'n2', target: 'n5', type: 'smoothstep' },
      { id: 'e2', source: 'n5', target: 'n4', type: 'smoothstep' },
      { id: 'e3', source: 'n4', target: 'n6', type: 'smoothstep' },
      { id: 'e4', source: 'n6', target: 'n3', type: 'smoothstep' },
      { id: 'e5', source: 'n3', target: 'n1', type: 'smoothstep', label: 'Intereses' },
      { id: 'e6', source: 'n1', target: 'n2', type: 'smoothstep', label: 'Intereses' },
    ],
  },
  {
    id: 6,
    nombre: 'P6 – Delivery / Intermediación Logística',
    descripcion: 'Intermediario que conecta restaurantes/tiendas con consumidores mediante entrega.',
    categoria: 'Plataforma',
    ejemplo: 'Rappi, Uber Eats, iFood',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(350, 250), data: { label: 'Plataforma Delivery', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(600, 150), data: { label: 'Consumidor', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(100, 150), data: { label: 'Restaurante', tipo: 'proveedor' } },
      { id: 'n4', type: 'bacNode', position: p(600, 350), data: { label: 'Repartidor', tipo: 'actor', actorTipo: 'usuario' } },
      { id: 'n5', type: 'bacNode', position: p(470, 150), data: { label: 'Canal D', tipo: 'canal', canalTipo: 'D', descripcion: 'Entrega física' } },
      { id: 'n6', type: 'bacNode', position: p(470, 350), data: { label: 'Canal M', tipo: 'canal', canalTipo: 'M', descripcion: 'Comisión + delivery fee' } },
      { id: 'n7', type: 'bacNode', position: p(230, 250), data: { label: 'Canal A', tipo: 'canal', canalTipo: 'A', descripcion: 'Incorporación comercios' } },
    ],
    edges: [
      { id: 'e1', source: 'n3', target: 'n7', type: 'smoothstep' },
      { id: 'e2', source: 'n7', target: 'n1', type: 'smoothstep' },
      { id: 'e3', source: 'n4', target: 'n5', type: 'smoothstep' },
      { id: 'e4', source: 'n5', target: 'n2', type: 'smoothstep' },
      { id: 'e5', source: 'n2', target: 'n6', type: 'smoothstep' },
      { id: 'e6', source: 'n6', target: 'n1', type: 'smoothstep' },
    ],
  },
  {
    id: 7,
    nombre: 'P7 – Educación',
    descripcion: 'Transformación de conocimiento en capacidades en los estudiantes.',
    categoria: 'Transformación',
    ejemplo: 'Universidad, academia online',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(100, 250), data: { label: 'Institución', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(500, 200), data: { label: 'Estudiante', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(100, 450), data: { label: 'Docente', tipo: 'actor', actorTipo: 'usuario' } },
      { id: 'n4', type: 'bacNode', position: p(300, 200), data: { label: 'Canal T', tipo: 'canal', canalTipo: 'T', descripcion: 'Formación / transformación' } },
      { id: 'n5', type: 'bacNode', position: p(300, 400), data: { label: 'Canal M', tipo: 'canal', canalTipo: 'M', descripcion: 'Matrícula / mensualidad' } },
      { id: 'n6', type: 'bacNode', position: p(500, 400), data: { label: 'Conocimiento', tipo: 'componente', descripcion: 'Contenidos y currícula' } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n4', type: 'smoothstep' },
      { id: 'e2', source: 'n3', target: 'n4', type: 'smoothstep' },
      { id: 'e3', source: 'n4', target: 'n2', type: 'smoothstep' },
      { id: 'e4', source: 'n2', target: 'n5', type: 'smoothstep' },
      { id: 'e5', source: 'n5', target: 'n1', type: 'smoothstep' },
      { id: 'e6', source: 'n6', target: 'n4', type: 'smoothstep' },
    ],
  },
  {
    id: 8,
    nombre: 'P8 – Agricultura',
    descripcion: 'Transformación de insumos naturales en productos agrícolas.',
    categoria: 'Transformación',
    ejemplo: 'Finca cafetera, agroindustria',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(100, 250), data: { label: 'Empresa Agrícola', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(500, 100), data: { label: 'Comprador B2B', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(100, 450), data: { label: 'Proveedor Insumos', tipo: 'proveedor' } },
      { id: 'n4', type: 'bacNode', position: p(280, 250), data: { label: 'Canal T', tipo: 'canal', canalTipo: 'T', descripcion: 'Producción agrícola' } },
      { id: 'n5', type: 'bacNode', position: p(400, 100), data: { label: 'Canal D', tipo: 'canal', canalTipo: 'D', descripcion: 'Distribución cosecha' } },
      { id: 'n6', type: 'bacNode', position: p(280, 450), data: { label: 'Canal A', tipo: 'canal', canalTipo: 'A', descripcion: 'Compra insumos' } },
      { id: 'n7', type: 'bacNode', position: p(500, 300), data: { label: 'Producto Agrícola', tipo: 'componente' } },
    ],
    edges: [
      { id: 'e1', source: 'n3', target: 'n6', type: 'smoothstep' },
      { id: 'e2', source: 'n6', target: 'n1', type: 'smoothstep' },
      { id: 'e3', source: 'n1', target: 'n4', type: 'smoothstep' },
      { id: 'e4', source: 'n4', target: 'n7', type: 'smoothstep' },
      { id: 'e5', source: 'n7', target: 'n5', type: 'smoothstep' },
      { id: 'e6', source: 'n5', target: 'n2', type: 'smoothstep' },
    ],
  },
  {
    id: 9,
    nombre: 'P9 – SaaS',
    descripcion: 'Software como servicio con suscripción recurrente.',
    categoria: 'Digital',
    ejemplo: 'Salesforce, Slack, Arcana Strata',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(100, 200), data: { label: 'Empresa SaaS', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(500, 150), data: { label: 'Usuario', tipo: 'actor', actorTipo: 'usuario' } },
      { id: 'n3', type: 'bacNode', position: p(500, 300), data: { label: 'Admin / Empresa', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n4', type: 'bacNode', position: p(300, 150), data: { label: 'Canal D-Digital', tipo: 'canal', canalTipo: 'D', descripcion: 'App / plataforma web' } },
      { id: 'n5', type: 'bacNode', position: p(300, 300), data: { label: 'Canal M-Suscripción', tipo: 'canal', canalTipo: 'M', descripcion: 'Cobro recurrente' } },
      { id: 'n6', type: 'bacNode', position: p(100, 400), data: { label: 'Plataforma', tipo: 'componente', descripcion: 'Infraestructura cloud' } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n4', type: 'smoothstep' },
      { id: 'e2', source: 'n4', target: 'n2', type: 'smoothstep' },
      { id: 'e3', source: 'n3', target: 'n5', type: 'smoothstep' },
      { id: 'e4', source: 'n5', target: 'n1', type: 'smoothstep' },
      { id: 'e5', source: 'n6', target: 'n4', type: 'smoothstep' },
      { id: 'e6', source: 'n1', target: 'n6', type: 'smoothstep' },
    ],
  },
  {
    id: 10,
    nombre: 'P10 – Soluciones a Medida',
    descripcion: 'Desarrollo de soluciones personalizadas para cada cliente.',
    categoria: 'Servicios',
    ejemplo: 'Consultoría, software a medida',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(100, 250), data: { label: 'Consultora', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(500, 200), data: { label: 'Cliente', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(300, 100), data: { label: 'Canal R', tipo: 'canal', canalTipo: 'R', descripcion: 'Diagnóstico y propuesta' } },
      { id: 'n4', type: 'bacNode', position: p(300, 250), data: { label: 'Canal T', tipo: 'canal', canalTipo: 'T', descripcion: 'Desarrollo solución' } },
      { id: 'n5', type: 'bacNode', position: p(300, 400), data: { label: 'Canal M', tipo: 'canal', canalTipo: 'M', descripcion: 'Cobro por proyecto' } },
      { id: 'n6', type: 'bacNode', position: p(100, 450), data: { label: 'Equipo Experto', tipo: 'recurso' } },
    ],
    edges: [
      { id: 'e1', source: 'n2', target: 'n3', type: 'smoothstep' },
      { id: 'e2', source: 'n3', target: 'n1', type: 'smoothstep' },
      { id: 'e3', source: 'n1', target: 'n4', type: 'smoothstep' },
      { id: 'e4', source: 'n4', target: 'n2', type: 'smoothstep' },
      { id: 'e5', source: 'n2', target: 'n5', type: 'smoothstep' },
      { id: 'e6', source: 'n5', target: 'n1', type: 'smoothstep' },
      { id: 'e7', source: 'n6', target: 'n4', type: 'smoothstep' },
    ],
  },
  {
    id: 11,
    nombre: 'P11 – Lotería / Apuestas',
    descripcion: 'Recaudo de capital de muchos y distribución a pocos ganadores.',
    categoria: 'Financiero',
    ejemplo: 'Lotería nacional, casino',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(300, 200), data: { label: 'Operador Lotería', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(550, 150), data: { label: 'Apostador', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(550, 350), data: { label: 'Ganador', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n4', type: 'bacNode', position: p(100, 200), data: { label: 'Pozo Acumulado', tipo: 'componente', descripcion: 'Reserva de premios' } },
      { id: 'n5', type: 'bacNode', position: p(420, 150), data: { label: 'Canal M-apuesta', tipo: 'canal', canalTipo: 'M', descripcion: 'Venta de boletos' } },
      { id: 'n6', type: 'bacNode', position: p(420, 350), data: { label: 'Canal D-premio', tipo: 'canal', canalTipo: 'D', descripcion: 'Entrega de premios' } },
    ],
    edges: [
      { id: 'e1', source: 'n2', target: 'n5', type: 'smoothstep' },
      { id: 'e2', source: 'n5', target: 'n4', type: 'smoothstep' },
      { id: 'e3', source: 'n4', target: 'n6', type: 'smoothstep' },
      { id: 'e4', source: 'n6', target: 'n3', type: 'smoothstep' },
      { id: 'e5', source: 'n1', target: 'n5', type: 'smoothstep' },
      { id: 'e6', source: 'n1', target: 'n6', type: 'smoothstep' },
    ],
  },
  {
    id: 12,
    nombre: 'P12 – Marketplace',
    descripcion: 'Plataforma bilateral que conecta compradores y vendedores independientes.',
    categoria: 'Plataforma',
    ejemplo: 'MercadoLibre, Amazon, Etsy',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(300, 250), data: { label: 'Marketplace', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(550, 100), data: { label: 'Comprador', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(550, 400), data: { label: 'Vendedor', tipo: 'actor', actorTipo: 'usuario' } },
      { id: 'n4', type: 'bacNode', position: p(100, 250), data: { label: 'Catálogo', tipo: 'componente', descripcion: 'Listados de productos' } },
      { id: 'n5', type: 'bacNode', position: p(420, 100), data: { label: 'Canal D', tipo: 'canal', canalTipo: 'D', descripcion: 'Descubrimiento y compra' } },
      { id: 'n6', type: 'bacNode', position: p(420, 400), data: { label: 'Canal M', tipo: 'canal', canalTipo: 'M', descripcion: 'Comisión por venta' } },
      { id: 'n7', type: 'bacNode', position: p(150, 450), data: { label: 'Canal A', tipo: 'canal', canalTipo: 'A', descripcion: 'Onboarding vendedores' } },
    ],
    edges: [
      { id: 'e1', source: 'n3', target: 'n7', type: 'smoothstep' },
      { id: 'e2', source: 'n7', target: 'n4', type: 'smoothstep' },
      { id: 'e3', source: 'n4', target: 'n5', type: 'smoothstep' },
      { id: 'e4', source: 'n5', target: 'n2', type: 'smoothstep' },
      { id: 'e5', source: 'n2', target: 'n6', type: 'smoothstep' },
      { id: 'e6', source: 'n6', target: 'n1', type: 'smoothstep' },
    ],
  },
  {
    id: 13,
    nombre: 'P13 – Franquicia',
    descripcion: 'Licenciamiento de modelo de negocio probado a operadores independientes.',
    categoria: 'Red',
    ejemplo: 'McDonald\'s, Subway',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(100, 200), data: { label: 'Franquiciador', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(500, 200), data: { label: 'Franquiciado', tipo: 'actor', actorTipo: 'usuario' } },
      { id: 'n3', type: 'bacNode', position: p(500, 400), data: { label: 'Cliente Final', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n4', type: 'bacNode', position: p(300, 100), data: { label: 'Canal A-licencia', tipo: 'canal', canalTipo: 'A', descripcion: 'Contrato franquicia' } },
      { id: 'n5', type: 'bacNode', position: p(300, 300), data: { label: 'Canal D-modelo', tipo: 'canal', canalTipo: 'D', descripcion: 'Transferencia know-how' } },
      { id: 'n6', type: 'bacNode', position: p(100, 400), data: { label: 'Marca & Know-how', tipo: 'componente' } },
    ],
    edges: [
      { id: 'e1', source: 'n2', target: 'n4', type: 'smoothstep' },
      { id: 'e2', source: 'n4', target: 'n1', type: 'smoothstep', label: 'Regalías' },
      { id: 'e3', source: 'n6', target: 'n5', type: 'smoothstep' },
      { id: 'e4', source: 'n5', target: 'n2', type: 'smoothstep' },
      { id: 'e5', source: 'n2', target: 'n3', type: 'smoothstep' },
    ],
  },
  {
    id: 14,
    nombre: 'P14 – Multinivel',
    descripcion: 'Red de distribución donde los distribuidores también reclutan nuevos distribuidores.',
    categoria: 'Red',
    ejemplo: 'Herbalife, Amway',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(100, 250), data: { label: 'Empresa Multinivel', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(400, 150), data: { label: 'Distribuidor L1', tipo: 'actor', actorTipo: 'usuario' } },
      { id: 'n3', type: 'bacNode', position: p(600, 150), data: { label: 'Distribuidor L2', tipo: 'actor', actorTipo: 'usuario' } },
      { id: 'n4', type: 'bacNode', position: p(600, 350), data: { label: 'Consumidor', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n5', type: 'bacNode', position: p(250, 150), data: { label: 'Canal D-red', tipo: 'canal', canalTipo: 'D', descripcion: 'Distribución en red' } },
      { id: 'n6', type: 'bacNode', position: p(250, 350), data: { label: 'Canal M-comisiones', tipo: 'canal', canalTipo: 'M', descripcion: 'Comisiones en cascada' } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n5', type: 'smoothstep' },
      { id: 'e2', source: 'n5', target: 'n2', type: 'smoothstep' },
      { id: 'e3', source: 'n2', target: 'n3', type: 'smoothstep' },
      { id: 'e4', source: 'n3', target: 'n4', type: 'smoothstep' },
      { id: 'e5', source: 'n4', target: 'n6', type: 'smoothstep' },
      { id: 'e6', source: 'n6', target: 'n1', type: 'smoothstep' },
    ],
  },
  {
    id: 15,
    nombre: 'P15 – Crowdfunding',
    descripcion: 'Financiación colectiva de proyectos por múltiples aportantes.',
    categoria: 'Financiero',
    ejemplo: 'Kickstarter, Indiegogo',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(300, 250), data: { label: 'Plataforma CF', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(550, 150), data: { label: 'Aportante', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(550, 350), data: { label: 'Creador Proyecto', tipo: 'actor', actorTipo: 'usuario' } },
      { id: 'n4', type: 'bacNode', position: p(100, 250), data: { label: 'Capital Colectivo', tipo: 'componente' } },
      { id: 'n5', type: 'bacNode', position: p(420, 150), data: { label: 'Canal M-aporte', tipo: 'canal', canalTipo: 'M', descripcion: 'Recaudo de aportes' } },
      { id: 'n6', type: 'bacNode', position: p(420, 350), data: { label: 'Canal D-fondos', tipo: 'canal', canalTipo: 'D', descripcion: 'Desembolso al creador' } },
    ],
    edges: [
      { id: 'e1', source: 'n2', target: 'n5', type: 'smoothstep' },
      { id: 'e2', source: 'n5', target: 'n4', type: 'smoothstep' },
      { id: 'e3', source: 'n4', target: 'n6', type: 'smoothstep' },
      { id: 'e4', source: 'n6', target: 'n3', type: 'smoothstep' },
      { id: 'e5', source: 'n1', target: 'n5', type: 'smoothstep' },
      { id: 'e6', source: 'n1', target: 'n6', type: 'smoothstep' },
    ],
  },
  {
    id: 16,
    nombre: 'P16 – Gobierno / Servicios Públicos',
    descripcion: 'Provisión de servicios financiados por impuestos o subsidios.',
    categoria: 'Público',
    ejemplo: 'Entidad pública, municipio',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(100, 250), data: { label: 'Entidad Pública', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(500, 150), data: { label: 'Ciudadano', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(100, 450), data: { label: 'Estado / Tesoro', tipo: 'proveedor' } },
      { id: 'n4', type: 'bacNode', position: p(300, 150), data: { label: 'Canal D-servicio', tipo: 'canal', canalTipo: 'D', descripcion: 'Prestación del servicio' } },
      { id: 'n5', type: 'bacNode', position: p(300, 400), data: { label: 'Canal A-presupuesto', tipo: 'canal', canalTipo: 'A', descripcion: 'Asignación presupuestal' } },
      { id: 'n6', type: 'bacNode', position: p(500, 350), data: { label: 'Presupuesto', tipo: 'componente' } },
    ],
    edges: [
      { id: 'e1', source: 'n3', target: 'n5', type: 'smoothstep' },
      { id: 'e2', source: 'n5', target: 'n6', type: 'smoothstep' },
      { id: 'e3', source: 'n6', target: 'n1', type: 'smoothstep' },
      { id: 'e4', source: 'n1', target: 'n4', type: 'smoothstep' },
      { id: 'e5', source: 'n4', target: 'n2', type: 'smoothstep' },
    ],
  },
  {
    id: 17,
    nombre: 'P17 – Información / Analítica',
    descripcion: 'Monetización de datos e insights como producto principal.',
    categoria: 'Digital',
    ejemplo: 'Bloomberg, Nielsen, bases de datos',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(100, 250), data: { label: 'Empresa Datos', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(500, 150), data: { label: 'Suscriptor', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(100, 450), data: { label: 'Fuente de Datos', tipo: 'proveedor' } },
      { id: 'n4', type: 'bacNode', position: p(300, 150), data: { label: 'Canal D-datos', tipo: 'canal', canalTipo: 'D', descripcion: 'Entrega de reportes/APIs' } },
      { id: 'n5', type: 'bacNode', position: p(300, 400), data: { label: 'Canal T-analítica', tipo: 'canal', canalTipo: 'T', descripcion: 'Procesamiento de datos' } },
      { id: 'n6', type: 'bacNode', position: p(300, 275), data: { label: 'Canal M', tipo: 'canal', canalTipo: 'M', descripcion: 'Suscripción a datos' } },
    ],
    edges: [
      { id: 'e1', source: 'n3', target: 'n5', type: 'smoothstep' },
      { id: 'e2', source: 'n5', target: 'n1', type: 'smoothstep' },
      { id: 'e3', source: 'n1', target: 'n4', type: 'smoothstep' },
      { id: 'e4', source: 'n4', target: 'n2', type: 'smoothstep' },
      { id: 'e5', source: 'n2', target: 'n6', type: 'smoothstep' },
      { id: 'e6', source: 'n6', target: 'n1', type: 'smoothstep' },
    ],
  },
  {
    id: 18,
    nombre: 'P18 – Publicidad',
    descripcion: 'Audiencia gratuita para usuarios; monetización por anunciantes.',
    categoria: 'Digital',
    ejemplo: 'Google, Facebook, periódico gratuito',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(300, 250), data: { label: 'Plataforma Media', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(550, 100), data: { label: 'Usuario', tipo: 'actor', actorTipo: 'usuario' } },
      { id: 'n3', type: 'bacNode', position: p(550, 400), data: { label: 'Anunciante', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n4', type: 'bacNode', position: p(100, 250), data: { label: 'Audiencia/Datos', tipo: 'componente' } },
      { id: 'n5', type: 'bacNode', position: p(430, 100), data: { label: 'Canal D-contenido', tipo: 'canal', canalTipo: 'D', descripcion: 'Contenido gratuito' } },
      { id: 'n6', type: 'bacNode', position: p(430, 400), data: { label: 'Canal M-ads', tipo: 'canal', canalTipo: 'M', descripcion: 'Venta de espacios publicitarios' } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n5', type: 'smoothstep' },
      { id: 'e2', source: 'n5', target: 'n2', type: 'smoothstep' },
      { id: 'e3', source: 'n2', target: 'n4', type: 'smoothstep' },
      { id: 'e4', source: 'n4', target: 'n6', type: 'smoothstep' },
      { id: 'e5', source: 'n3', target: 'n6', type: 'smoothstep' },
      { id: 'e6', source: 'n6', target: 'n1', type: 'smoothstep' },
    ],
  },
  {
    id: 19,
    nombre: 'P19 – Suscripción',
    descripcion: 'Acceso continuo a contenido o servicios por pago recurrente.',
    categoria: 'Digital',
    ejemplo: 'Netflix, Spotify, revistas',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(100, 250), data: { label: 'Empresa Suscripción', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(500, 200), data: { label: 'Suscriptor', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(100, 450), data: { label: 'Creadores/Proveedores', tipo: 'proveedor' } },
      { id: 'n4', type: 'bacNode', position: p(300, 150), data: { label: 'Canal D-streaming', tipo: 'canal', canalTipo: 'D', descripcion: 'Acceso continuo contenido' } },
      { id: 'n5', type: 'bacNode', position: p(300, 350), data: { label: 'Canal M-suscripción', tipo: 'canal', canalTipo: 'M', descripcion: 'Cobro recurrente mensual' } },
      { id: 'n6', type: 'bacNode', position: p(500, 400), data: { label: 'Catálogo Contenido', tipo: 'componente' } },
    ],
    edges: [
      { id: 'e1', source: 'n3', target: 'n6', type: 'smoothstep' },
      { id: 'e2', source: 'n6', target: 'n4', type: 'smoothstep' },
      { id: 'e3', source: 'n1', target: 'n4', type: 'smoothstep' },
      { id: 'e4', source: 'n4', target: 'n2', type: 'smoothstep' },
      { id: 'e5', source: 'n2', target: 'n5', type: 'smoothstep' },
      { id: 'e6', source: 'n5', target: 'n1', type: 'smoothstep' },
    ],
  },
  {
    id: 20,
    nombre: 'P20 – Economía Circular',
    descripcion: 'Ciclos de vida extendidos: reparación, reciclaje, remanufactura.',
    categoria: 'Sostenibilidad',
    ejemplo: 'Patagonia WornWear, Renault Remanufacturing',
    nodes: [
      { id: 'n1', type: 'bacNode', position: p(300, 250), data: { label: 'Empresa Circular', tipo: 'negocio' } },
      { id: 'n2', type: 'bacNode', position: p(550, 100), data: { label: 'Consumidor', tipo: 'actor', actorTipo: 'cliente' } },
      { id: 'n3', type: 'bacNode', position: p(550, 400), data: { label: 'Reciclador', tipo: 'proveedor' } },
      { id: 'n4', type: 'bacNode', position: p(100, 250), data: { label: 'Material Recuperado', tipo: 'componente' } },
      { id: 'n5', type: 'bacNode', position: p(420, 100), data: { label: 'Canal D-producto', tipo: 'canal', canalTipo: 'D', descripcion: 'Venta producto nuevo/reparado' } },
      { id: 'n6', type: 'bacNode', position: p(420, 400), data: { label: 'Canal RT-retorno', tipo: 'canal', canalTipo: 'RT', descripcion: 'Retorno de producto usado' } },
      { id: 'n7', type: 'bacNode', position: p(300, 450), data: { label: 'Canal T-circular', tipo: 'canal', canalTipo: 'T', descripcion: 'Remanufactura/reciclaje' } },
    ],
    edges: [
      { id: 'e1', source: 'n1', target: 'n5', type: 'smoothstep' },
      { id: 'e2', source: 'n5', target: 'n2', type: 'smoothstep' },
      { id: 'e3', source: 'n2', target: 'n6', type: 'smoothstep' },
      { id: 'e4', source: 'n6', target: 'n3', type: 'smoothstep' },
      { id: 'e5', source: 'n3', target: 'n7', type: 'smoothstep' },
      { id: 'e6', source: 'n7', target: 'n4', type: 'smoothstep' },
      { id: 'e7', source: 'n4', target: 'n1', type: 'smoothstep' },
    ],
  },
]
